# FICHIER CUSTOM POUR CobbleRayou

[ejs.app]
title = "Launcher CobbleRayou"

[ejs.landing]
mediaGitHubURL = "https://cobblerayou.fr"
mediaTwitterURL = "#"
mediaInstagramURL = ""
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discordapp.com/invite/fpeNacEmeg"

[ejs.settings]
sourceGithubLink = "https://cobblerayou.fr"
supportLink = "https://cobblerayou.fr"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR COBBLERAYOU"
welcomeDescription = "Découvrez notre serveur Cobblemon intégrant tous les modèles pour une expérience complète ! Profitez d'une économie stable et équilibrée au sein d'une communauté active et soudée qui aime partager. Avec des événements réguliers et des ajouts inédits exclusifs, votre aventure ne s'arrête jamais. Rejoignez-nous pour vivre le meilleur du moddé avec des dresseurs passionnés !"
welcomeDescCTA = ""
